# Generated by Django 2.2.3 on 2019-07-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='название на русском')),
                ('title_en', models.CharField(max_length=200, verbose_name='название на английском')),
                ('title_jp', models.CharField(max_length=200, verbose_name='название на японском')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка покемона')),
                ('description', models.TextField(verbose_name='описание')),
                ('next_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_life_stage', to='pokemon_entities.Pokemon', verbose_name='следующая стадия развития покемона')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_life_stage', to='pokemon_entities.Pokemon', verbose_name='предыдущая стадия развития покемона')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('appeared_at', models.DateTimeField(verbose_name='дата и время появления на карте')),
                ('disappeared_at', models.DateTimeField(verbose_name='дата и время удаления с карты')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='здоровье')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='сила')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon', verbose_name='покемон')),
            ],
        ),
    ]
